spring:
  kafka:
    bootstrap-servers: broker1:9092,broker2:9092,broker3:9092

twitter:
  poll:
    interval-seconds: 10
    delay-seconds: 10
  api:
    bearer-token: ""
  query:
    tweets-number: 10
    filters: "-is:retweet lang:en place_country:US"
    fields: "created_at,lang,public_metrics,source,geo,text"
  monitored-topics:
    AAPL: [ apple, iphone, aapl, macbook ]
    Inflation: [ inflation, "interest rates" ]
